apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: django-s2i
objects:
- apiVersion: v1
  data:
    DB_PASS: pass
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: test-config
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: django-ex
      name: django-s2i-cron
    name: django-ex
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/test-rucio-opint-backend-2/django-ex:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2019-08-24T17:48:53Z
    creationTimestamp: null
    generation: 2
    labels:
      app: django-ex
      name: django-s2i-cron
    name: source-s2i-python
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: maany/source-s2i-python
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/test-rucio-opint-backend-2/source-s2i-python:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: django-ex
      name: django-s2i-cron
    name: django-ex
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: django-ex:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/maany/django-ex
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: source-s2i-python:latest
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: G79Fxcg4H61A0_Xe0VBi
      type: GitHub
    - generic:
        secret: hjqwntPGojc8A07iPCXB
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 3
    labels:
      app: django-ex
      name: django-s2i-cron
    name: django-ex
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: django-ex
      deploymentconfig: django-ex
      name: django-s2i-cron
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: django-ex
          deploymentconfig: django-ex
          name: django-s2i-cron
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: test-config
          image: docker-registry.default.svc:5000/test-rucio-opint-backend-2/django-ex@sha256:f9b04a867cf77a12ea24b759fd15853793c958daccd57c4938cf16336d500dd6
          imagePullPolicy: Always
          name: django-ex
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - django-ex
        from:
          kind: ImageStreamTag
          name: django-ex:latest
          namespace: test-rucio-opint-backend-2
        lastTriggeredImage: docker-registry.default.svc:5000/test-rucio-opint-backend-2/django-ex@sha256:f9b04a867cf77a12ea24b759fd15853793c958daccd57c4938cf16336d500dd6
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: django-ex
      name: django-s2i-cron
    name: django-ex
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: django-ex
      deploymentconfig: django-ex
      name: django-s2i-cron
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
